### ISSUE TITLE
push FMS update from /g/data/ik11/spack/0.19.0?

### ISSUE THREAD

**Issue by aekiss** [COSIMA/spack-config#1]
Just a note that the repo in `/g/data/ik11/spack/0.19.0` has an uncommitted FMS update - should this be committed and pushed here?

**Comment by micaeljtoliveira** [comment]
I've committed the changes, but since the main branch now uses Spack 0.20.1, I've decided to create a branch for our Spack 0.19.0 environments. This is for reproducibility and record-keeping.
